[pytest]

addopts = 
        --base-url=https://eventhub.rahulshettyacademy.com/
        --browser=chromium
        --screenshot=only-on-failure
        --video=retain-on-failure
        --tracing=retain-on-failure
        --html=reports/report.html
        --self-contained-html
        -v

testpaths=tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*

markers = 
    smoke:quick smoke-suite subset
    regression: full regression suite
    home: home page tests
    login: login page tests
    register: register page tests
    
